global:
  scrape_interval:     3s

  external_labels:
      monitor: 'nats-surveyor'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'surveyor'
    scrape_interval: 5s
    static_configs:
      - targets: ['surveyor:7777']
  - job_name: 'vector'
    scrape_interval: 5s
    static_configs:
      - targets: ['vector:9090']
  - job_name: 'exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nats-exporter:7777']