sources:
  dlq_monitor:
    type: nats
    connection_name: dlq_monitor
    subject: $$JS.EVENT.ADVISORY.CONSUMER.MAX_DELIVERIES.teststream.test-fraud-call-logs-consumer
    url: nats://nats:4222
    queue: vector-dlq-monitor
    auth:
      strategy: user_password
      user_password:
        user: nats
        password: rubber-hose

transforms:
  log_to_metric_transform:
    type: log_to_metric
    inputs:
    - dlq_monitor
    metrics:
      - type: "counter"
        name: "nats_dlq_message_count"
        field: "subject"
        tags:
          subject: "{{ subject }}"

sinks:
  prometheus:
    type: prometheus_exporter
    inputs: 
    - log_to_metric_transform
    address: "0.0.0.0:9090"
  dlq_msg:
    encoding:
      codec: json
    type: console
    inputs:
      - dlq_monitor